# Generated by Django 5.1.5 on 2025-05-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="streak",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="weekly_card_count_goal",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
