# Generated by Django 5.1.1 on 2024-12-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decks", "0003_alter_deck_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deck",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
