# Generated by Django 5.1.1 on 2025-01-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="is_correct",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
