# Generated by Django 5.1.1 on 2025-01-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study_sessions", "0002_alter_response_is_correct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="is_correct",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
