# Generated by Django 5.1.1 on 2025-01-05 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study_sessions", "0004_alter_studysession_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
